### ISSUE TITLE
Not able to start "npm start"

### ISSUE THREAD

**Issue by Antibioticvz** [lamosty/lexi#1]
I've got this error message 

Microsoft Windows [Version 6.3.9600](c) 2013 Microsoft Corporation. All rights reserved.

B:\xampp\apps\wordpress\htdocs\wp-content\themes>cd lexi

B:\xampp\apps\wordpress\htdocs\wp-content\themes\lexi>npm start

> Lexi-WP-Theme@0.0.1 start B:\xampp\apps\wordpress\htdocs\wp-content\themes\lexi
> npm run build && node server.js
> 
> Lexi-WP-Theme@0.0.1 build B:\xampp\apps\wordpress\htdocs\wp-content\themes\lexi
> npm run clean && webpack
> 
> Lexi-WP-Theme@0.0.1 clean B:\xampp\apps\wordpress\htdocs\wp-content\themes\lexi
> rm -rf dist

'rm' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "B:\nodejs\node.exe" "B:\nodejs\node_modules\npm\bin\npm-cli.js" "run" "clean"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! Lexi-WP-Theme@0.0.1 clean: `rm -rf dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Lexi-WP-Theme@0.0.1 clean script 'rm -rf dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Lexi-WP-Theme package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf dist
npm ERR! You can get their info via:
npm ERR!     npm owner ls Lexi-WP-Theme
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     B:\xampp\apps\wordpress\htdocs\wp-content\themes\lexi\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "B:\nodejs\node.exe" "B:\nodejs\node_modules\npm\bin\npm-cli.js" "run" "build"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! Lexi-WP-Theme@0.0.1 build: `npm run clean && webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Lexi-WP-Theme@0.0.1 build script 'npm run clean && webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Lexi-WP-Theme package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && webpack
npm ERR! You can get their info via:
npm ERR!     npm owner ls Lexi-WP-Theme
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     B:\xampp\apps\wordpress\htdocs\wp-content\themes\lexi\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "B:\nodejs\node.exe" "B:\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! Lexi-WP-Theme@0.0.1 start: `npm run build && node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Lexi-WP-Theme@0.0.1 start script 'npm run build && node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Lexi-WP-Theme package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls Lexi-WP-Theme
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     B:\xampp\apps\wordpress\htdocs\wp-content\themes\lexi\npm-debug.log

B:\xampp\apps\wordpress\htdocs\wp-content\themes\lexi>

**Comment by lamosty** [comment]
Yeah, I completely forgot that Windows doesn't support the `rm` command which deletes files/folders. I'll fix this soon by using the [rimraf](https://github.com/isaacs/rimraf) Node module instead of `rm`.

Thanks for reporting this!
